export const products = [
  { 
    id: 1, 
    name: 'Paracetamol 500mg', 
    manufacturer: 'Cipla Ltd', 
    price: 45, 
    originalPrice: 60, 
    image: 'https://assets.truemeds.in/Images/ProductImage/TM-TACR1-030464/paracip-500-tablet-10_paracip-500-tablet-10--TM-TACR1-030464_1.png?width=320',
    discount: 25,
    category: 'Pain Relief',
    subcategory: 'Fever',
    condition: "Cold & Cough",
    status: 'In Stock',
    unitsAvailable: 255,
    rxRequired: false,
    description: "Used to treat mild to moderate pain (from headaches, menstrual periods, toothaches) and to reduce fever.",
    dosage: "Adults: 1 to 2 tablets every 4 to 6 hours as needed.",
    sideEffects: ["Nausea", "Allergic reaction", "Stomach pain"],
    precautions: ["Do not exceed the recommended dose.", "Consult a doctor if you have liver or kidney problems."]
  },
  { 
    id: 2, 
    name: 'Cough Syrup 100ml', 
    manufacturer: 'Dabur India Ltd', 
    price: 85, 
    originalPrice: 110, 
    image: 'https://assets.truemeds.in/Images/ProductImage/TM-SYUP1-008504/dabur-honitus-herbal-cough-remedy-syrup-100ml_dabur-honitus-herbal-cough-remedy-syrup-100ml--TM-SYUP1-008504_1.png?width=320',
    discount: 23,
    category: 'Cold & Flu',
    subcategory: 'Cough',
    condition: "Cold & Cough",
    status: 'In Stock',
    unitsAvailable: 180,
    rxRequired: false,
    description: "An Ayurvedic formula that provides effective relief from cough and throat irritation without causing drowsiness.",
    dosage: "Adults: 2 teaspoons, 3-4 times a day.",
    sideEffects: ["Dizziness", "Upset stomach"],
    precautions: ["Not recommended for children under 6 years.", "Shake well before use."]
  },
  { 
    id: 3, 
    name: 'Cetirizine 10mg', 
    manufacturer: "Dr. Reddy's", 
    price: 38, 
    originalPrice: 50, 
    image: 'https://assets.truemeds.in/Images/ProductImage/TM-TACR1-053315/cetzine-tablet-15_cetzine-tablet-15--TM-TACR1-053315_1.png?width=320',
    discount: 24,
    category: 'Allergy Relief',
    subcategory: 'Antihistamine',
    condition: "Cold & Cough",
    status: 'In Stock',
    unitsAvailable: 400,
    rxRequired: false,
    description: "An antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, itching eyes/nose, sneezing, hives, and itching.",
    dosage: "Adults: 1 tablet once daily.",
    sideEffects: ["Drowsiness", "Tiredness", "Dry mouth"],
    precautions: ["Avoid driving or operating heavy machinery.", "Consult a doctor before use during pregnancy."]
  },
  { 
    id: 4, 
    name: 'Vitamin C Tablets', 
    manufacturer: 'Himalaya', 
    price: 120, 
    originalPrice: 150, 
    image: 'https://assets.truemeds.in/Images/ProductImage/TM-TACR1-021892/limcee-orange-flavour-chewable-tablet-15_limcee-orange-flavour-chewable-tablet-15--TM-TACR1-021892_1.png?width=240',
    discount: 20,
    category: 'Nutritional Drinks & Supplements',
    subcategory: 'Vitamins',
    status: 'In Stock',
    unitsAvailable: 500,
    rxRequired: false,
    description: "Chewable Vitamin C tablets to boost immunity and maintain daily health. Rich in antioxidants.",
    dosage: "1 tablet daily or as directed by the physician.",
    sideEffects: ["Generally safe", "High doses may cause an upset stomach"],
    precautions: ["Store in a cool, dry place away from direct sunlight."]
  },
  { 
    id: 5, 
    name: 'Combiflam', 
    manufacturer: 'Sanofi India Ltd.', 
    price: 45, 
    originalPrice: 60, 
    image: 'https://assets.truemeds.in/Images/ProductImage/TM-TACR1-009412/combiflam-tablet-20_combiflam-tablet-20--TM-TACR1-009412_1.png?width=320',
    discount: 25,
    category: 'Pain Relief',
    subcategory: 'Painkiller',
    condition: "Cold & Cough",
    status: 'In Stock',
    unitsAvailable: 210,
    rxRequired: true,
    description: "A combination of Ibuprofen and Paracetamol used to relieve pain and inflammation.",
    dosage: "1 tablet after meals, up to 3 times a day.",
    sideEffects: ["Acidity", "Heartburn", "Nausea"],
    precautions: ["Not recommended on an empty stomach.", "Inform your doctor about any kidney or liver disease."]
  },
  { 
    id: 6, 
    name: 'Ketorol-DT', 
    manufacturer: 'Dr Reddys Laboratories Ltd', 
    price: 141, 
    originalPrice: 177, 
    image: 'https://assets.truemeds.in/Images/ProductImage/TM-TAER1-000533/ketorol-dt-tablet-15_ketorol-dt-tablet-15--TM-TAER1-000533_1.png?width=320',
    discount: 20,
    category: 'Pain Relief',
    subcategory: 'Painkiller',
    status: 'In Stock',
    unitsAvailable: 80,
    rxRequired: true,
    description: "A non-steroidal anti-inflammatory drug (NSAID) used for the short-term treatment of moderate to severe pain.",
    dosage: "As directed by the physician. Dissolve tablet in water before taking.",
    sideEffects: ["Headache", "Drowsiness", "Indigestion"],
    precautions: ["Use for the shortest duration possible.", "May increase risk of heart attack or stroke with long-term use."]
  },
  { 
    id: 7, 
    name: 'Ostoshine Tablet', 
    manufacturer: "Sun Pharmaceutical Industries Ltd", 
    price: 625, 
    originalPrice: 785, 
    image: 'https://assets.truemeds.in/Images/ProductImage/TM-TACR1-051298/ostoshine-tablet-10_ostoshine-tablet-10--TM-TACR1-051298_1.png?width=320',
    discount: 20,
    category: 'Nutritional Drinks & Supplements',
    subcategory: 'Minerals',
    status: 'In Stock',
    unitsAvailable: 110,
    rxRequired: false,
    description: "A nutritional supplement used for bone health, containing Calcium, Vitamin D3, and other minerals.",
    dosage: "1 tablet per day, or as directed by a healthcare professional.",
    sideEffects: ["Constipation", "Upset stomach"],
    precautions: ["Consult a doctor if you have a history of kidney stones."]
  },
  { 
    id: 8, 
    name: 'Neurobion Forte', 
    manufacturer: 'Procter & Gamble', 
    price: 36, 
    originalPrice: 46, 
    image: 'https://assets.truemeds.in/Images/ProductImage/TM-TACR1-048497/neurobion-forte-tablet-30_neurobion-forte-tablet-30--TM-TACR1-048497_1.png?width=320',
    discount: 22,
    category: 'Nutritional Drinks & Supplements',
    subcategory: 'Vitamins',
    condition: "Bone & Joint",
    status: 'In Stock',
    unitsAvailable: 700,
    rxRequired: false,
    description: "A multivitamin supplement containing a mixture of B vitamins. It is used to treat or prevent vitamin B deficiency.",
    dosage: "1 tablet daily.",
    sideEffects: ["Generally well-tolerated."],
    precautions: ["Store in a cool and dry place."]
  },
  { 
    id: 9, 
    name: 'Cipcal 500 Tablet', 
    manufacturer: 'Cipla Ltd', 
    price: 94, 
    originalPrice: 104, 
    image: 'https://assets.truemeds.in/Images/ProductImage/TM-TACR1-008255/cipcal-500-tablet-15_cipcal-500-tablet-15--TM-TACR1-008255_1.png?width=320',
    discount: 10,
    category: 'Nutritional Drinks & Supplements',
    subcategory: 'Minerals',
    status: 'In Stock',
    unitsAvailable: 250,
    rxRequired: false,
    description: "A calcium and Vitamin D3 supplement used to prevent or treat low blood calcium levels in people who do not get enough calcium from their diets.",
    dosage: "1 to 2 tablets daily.",
    sideEffects: ["Gas", "Bloating"],
    precautions: ["Inform your doctor of any pre-existing medical conditions."]
  },
  { 
    id: 10, 
    name: 'E-Vitamin 400 Capsule', 
    manufacturer: 'Prevego Healthcare', 
    price: 27, 
    originalPrice: 41, 
    image: 'https://assets.truemeds.in/Images/ProductImage/TM-CACR1-009847/e-vitamin-400-capsule-10_e-vitamin-400-capsule-10--TM-CACR1-009847_1.png?width=320',
    discount: 34,
    category: 'Nutritional Drinks & Supplements',
    subcategory: 'Vitamins',
    status: 'In Stock',
    unitsAvailable: 400,
    rxRequired: false,
    description: "Vitamin E supplement capsules that act as an antioxidant, helping to protect cells from damage.",
    dosage: "One capsule daily after a meal.",
    sideEffects: ["Fatigue", "Headache"],
    precautions: ["Consult your doctor before use if you are on blood-thinning medication."]
  },
  { 
    id: 11, 
    name: 'Dolo 650 Tablet', 
    manufacturer: "Micro Labs Ltd", 
    price: 29, 
    originalPrice: 33, 
    image: 'https://assets.truemeds.in/Images/ProductImage/TM-TACR1-011691/dolo-650-tablet-15_dolo-650-tablet-15--TM-TACR1-011691_1.png?width=320',
    discount: 12,
    category: 'Pain Relief',
    subcategory: 'Fever',
    status: 'In Stock',
    unitsAvailable: 1200,
    rxRequired: false,
    description: "A higher dose of paracetamol for effective relief from pain and high fever.",
    dosage: "Adults: 1 tablet every 6 hours. Do not exceed 4 tablets in 24 hours.",
    sideEffects: ["Nausea", "Stomach pain"],
    precautions: ["Overdose can be injurious to the liver.", "Keep out of reach of children."]
  },
  { 
    id: 12, 
    name: 'Crocin Advance Tablet', 
    manufacturer: 'Glaxosmithkline', 
    price: 18, 
    originalPrice: 20, 
    image: 'https://assets.truemeds.in/Images/ProductImage/TM-TACR1-053143/crocin-advance-tablet-20_crocin-advance-tablet-20--TM-TACR1-053143_1.png?width=320',
    discount: 10,
    category: 'Pain Relief',
    subcategory: 'Fever',
    status: 'In Stock',
    unitsAvailable: 950,
    rxRequired: false,
    description: "Contains paracetamol with Optizorb technology for faster absorption and pain relief.",
    dosage: "1-2 tablets every 4-6 hours.",
    sideEffects: ["Skin rash", "Itching"],
    precautions: ["Do not use with other products containing paracetamol."]
  },
  { 
    id: 13, 
    name: 'Saridon New Tablet', 
    manufacturer: 'Bayer Pharmaceuticals', 
    price: 45, 
    originalPrice: 50, 
    image: 'https://assets.truemeds.in/Images/ProductImage/TM-TACR1-079870/new-saridon-tablet-10_new-saridon-tablet-10--TM-TACR1-079870_1.png?width=320',
    discount: 10,
    category: 'Pain Relief',
    subcategory: 'Painkiller',
    status: 'In Stock',
    unitsAvailable: 600,
    rxRequired: false,
    description: "A triple-action formula for effective relief from headaches.",
    dosage: "1 tablet every 4-6 hours. Not to exceed 3 tablets in a day.",
    sideEffects: ["Allergic reactions", "Restlessness"],
    precautions: ["Not recommended for children below 12 years."]
  },
  { 
    id: 14, 
    name: 'Himalaya Himplasia Tablet', 
    manufacturer: 'Himalaya Wellness Company', 
    price: 249, 
    originalPrice: 262, 
    image: 'https://assets.truemeds.in/Images/ProductImage/TM-TACR1-047681/himalaya-himplasia-tablet-30_himalaya-himplasia-tablet-30--TM-TACR1-047681_1.png?width=320',
    discount: 5,
    category: 'Men Care',
    subcategory: 'Wellness',
    status: 'In Stock',
    unitsAvailable: 75,
    rxRequired: false,
    description: "An Ayurvedic formulation that helps maintain prostate health and urinary wellness in men.",
    dosage: "1 tablet twice daily, or as directed by your physician.",
    sideEffects: ["Generally safe with no side effects."],
    precautions: ["To be taken under medical supervision."]
  },
  { 
    id: 15, 
    name: 'Zincovit Tablet', 
    manufacturer: "Apex Laboratories Ltd.", 
    price: 92, 
    originalPrice: 115, 
    image: 'https://assets.truemeds.in/Images/ProductImage/TM-TACR1-044993/zincovit-tablet-15_zincovit-tablet-15--TM-TACR1-044993_1.png?width=320',
    discount: 20,
    category: 'Nutritional Drinks & Supplements',
    subcategory: 'Vitamins',
    status: 'In Stock',
    unitsAvailable: 450,
    rxRequired: false,
    description: "A multivitamin and multimineral supplement with Zinc to boost immunity and overall well-being.",
    dosage: "One tablet a day, or as directed by the physician.",
    sideEffects: ["Upset stomach", "Headache"],
    precautions: ["Do not exceed the recommended daily usage."]
  },
  { 
    id: 16, 
    name: 'Folitas Tablet', 
    manufacturer: 'Intas Pharmaceuticals Ltd', 
    price: 25, 
    originalPrice: 50, 
    image: 'https://assets.truemeds.in/Images/ProductImage/TM-TACR1-016107/folitas-tablet-30_folitas-tablet-30--TM-TACR1-016107_1.png?width=320',
    discount: 50,
    category: 'Nutritional Drinks & Supplements',
    subcategory: 'Vitamins',
    status: 'In Stock',
    unitsAvailable: 320,
    rxRequired: true,
    description: "Contains Folic Acid (Vitamin B9), essential for numerous body functions, including cell growth and development.",
    dosage: "As prescribed by the doctor.",
    sideEffects: ["Nausea", "Loss of appetite"],
    precautions: ["Inform your doctor about your medical history."]
  },
  {
    "id": 17,
    "name": "Whey Protein Powder 1kg",
    "manufacturer": "Optimum Nutrition",
    "price": 4500,
    "originalPrice": 6000,
    "discount": 25,
    "category": "Nutritional Drinks & Supplements",
    "subcategory": "Protein Drinks",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 80,
    "rxRequired": false,
    "description": "High-quality whey protein for muscle growth and recovery. Contains 24g of protein per serving.",
    "dosage": "Mix 1 scoop with 180-240ml of cold water or milk.",
    "sideEffects": ["Bloating", "Gas for lactose intolerant individuals"],
    "precautions": ["Not intended for medicinal use.", "Keep out of reach of children."]
  },
  {
    "id": 18,
    "name": "Maternity Pads",
    "manufacturer": "Mothercare",
    "price": 350,
    "originalPrice": 400,
    "discount": 12,
    "category": "Women Care",
    "subcategory": "Pregnancy Care",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 130,
    "rxRequired": false,
    "description": "Extra-absorbent pads designed for post-natal use, providing comfort and protection.",
    "dosage": "N/A",
    "sideEffects": ["N/A"],
    "precautions": ["Change regularly to maintain hygiene."]
  },
  {
    "id": 19,
    "name": "Electric Toothbrush",
    "manufacturer": "Oral-B",
    "price": 2500,
    "originalPrice": 3000,
    "discount": 17,
    "category": "Personal Care",
    "subcategory": "Oral Care",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 65,
    "rxRequired": false,
    "description": "Removes more plaque than a regular manual toothbrush with oscillating and rotating technology.",
    "dosage": "Brush for 2 minutes, twice a day.",
    "sideEffects": ["N/A"],
    "precautions": ["Replace brush head every 3 months."]
  },
  {
    "id": 20,
    "name":"Blood Pressure Monitor",
    "manufacturer": "Accu-Chek",
    "price": 900,
    "originalPrice": 1200,
    "discount": 25,
    "category": "Health Devices",
    "subcategory": "Blood Pressure Monitor",
    "image": "/images/placeholder.jpg",
    "status": "Low Stock",
    "unitsAvailable": 15,
    "rxRequired": true,
    "description": "A reliable blood glucose monitoring system for easy and accurate testing of blood sugar levels.",
    "dosage": "N/A",
    "sideEffects": ["N/A"],
    "precautions": ["Use with compatible test strips.", "Store in a dry place."]
  },
  {
    "id": 21,
    "name": "Intimate Wash 100ml",
    "manufacturer": "VWash",
    "price": 180,
    "originalPrice": 200,
    "discount": 10,
    "category": "Women Care",
    "subcategory": "Feminine Hygiene",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 220,
    "rxRequired": false,
    "description": "A pH-balanced intimate wash to maintain vaginal hygiene and prevent irritation or dryness.",
    "dosage": "Use a small amount daily during bathing.",
    "sideEffects": ["Rarely, skin irritation may occur."],
    "precautions": ["For external use only."]
  },
  {
    "id": 22,
    "name": "Sunscreen SPF 50",
    "manufacturer": "Neutrogena",
    "price": 550,
    "originalPrice": 650,
    "discount": 15,
    "category": "Personal Care",
    "subcategory": "Body Care",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 140,
    "rxRequired": false,
    "description": "Broad-spectrum SPF 50 sunscreen with Helioplex Technology for superior protection against sun damage.",
    "dosage": "Apply generously 15 minutes before sun exposure.",
    "sideEffects": ["Skin irritation in rare cases."],
    "precautions": ["Reapply every 2 hours, and after swimming or sweating."]
  },
  {
    "id": 23,
    "name": "Ayurvedic Hair Oil",
    "manufacturer": "Indulekha",
    "price": 380,
    "originalPrice": 432,
    "discount": 12,
    "category": "Personal Care",
    "subcategory": "Hair Care",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 95,
    "rxRequired": false,
    "description": "An Ayurvedic proprietary medicine recommended for the regulation of hair and scalp conditions like hair fall, dandruff etc.",
    "dosage": "Apply directly to scalp using the comb applicator.",
    "sideEffects": ["N/A"],
    "precautions": ["A patch test is recommended before use."]
  },
  {
    "id": 24,
    "name": "Digital Thermometer",
    "manufacturer": "Generic",
    "price": 1200,
    "originalPrice": 1500,
    "discount": 20,
    "category": "Health Devices",
    "subcategory": "Thermometer",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 40,
    "rxRequired": false,
    "description": "Measures your blood oxygen saturation (SpO2) and pulse rate quickly and accurately.",
    "dosage": "N/A",
    "sideEffects": ["N/A"],
    "precautions": ["Not for continuous monitoring.", "Ensure finger is clean and dry."]
  },
  {
    "id": 25,
    "name": "Green Tea (100 Bags)",
    "manufacturer": "Lipton",
    "price": 450,
    "originalPrice": 500,
    "discount": 10,
    "category": "Nutritional Drinks & Supplements",
    "subcategory": "Wellness",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 160,
    "rxRequired": false,
    "description": "A light and refreshing green tea, rich in antioxidants to support a healthy lifestyle.",
    "dosage": "Infuse one tea bag in hot water for 2-3 minutes.",
    "sideEffects": ["N/A"],
    "precautions": ["Best consumed without milk or sugar."]
  },
  {
    "id": 26,
    "name": "Antiseptic Liquid 250ml",
    "manufacturer": "Dettol",
    "price": 150,
    "originalPrice": 165,
    "discount": 9,
    "category": "First Aid",
    "subcategory": "Disinfectant",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 300,
    "rxRequired": false,
    "description": "A proven safe and effective concentrated antiseptic disinfectant that kills bacteria and provides protection against germs.",
    "dosage": "Dilute before use as per instructions on the label.",
    "sideEffects": ["Skin irritation if used undiluted."],
    "precautions": ["For external use only. Keep out of reach of children."]
  },
  {
    "id": 27,
    "name": "Hand Sanitizer 500ml",
    "manufacturer": "Lifebuoy",
    "price": 200,
    "originalPrice": 250,
    "discount": 20,
    "category": "Personal Care",
    "subcategory": "Hand Care",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 450,
    "rxRequired": false,
    "description": "Kills 99.9% of germs without water. Contains moisturizers and Vitamin E.",
    "dosage": "Apply a small amount to your palm and rub hands together until dry.",
    "sideEffects": ["Dryness of skin with excessive use."],
    "precautions": ["Flammable. Keep away from fire or flame."]
  },
  {
    "id": 28,
    "name": "Omega-3 Fish Oil",
    "manufacturer": "HealthKart",
    "price": 450,
    "originalPrice": 600,
    "discount": 25,
    "category": "Nutritional Drinks & Supplements",
    "subcategory": "Minerals",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 120,
    "rxRequired": false,
    "description": "Provides essential omega-3 fatty acids, which are beneficial for heart, brain, and joint health.",
    "dosage": "One capsule daily with a meal.",
    "sideEffects": ["Fishy aftertaste", "Upset stomach"],
    "precautions": ["Consult your physician before use if you are pregnant or nursing."]
  },
  {
    "id": 29,
    "name": "Maternity Pads (Large)",
    "manufacturer": "Mothercare",
    "price": 350,
    "originalPrice": 400,
    "discount": 12,
    "category": "Women Care",
    "subcategory": "Pregnancy Care",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 90,
    "rxRequired": false,
    "description": "Extra-absorbent pads designed for post-natal use, providing comfort and protection.",
    "dosage": "N/A",
    "sideEffects": ["N/A"],
    "precautions": ["Change regularly to maintain hygiene."]
  },
  {
    "id": 30,
    "name": "Band-Aid Pack (100 pcs)",
    "manufacturer": "Johnson & Johnson",
    "price": 90,
    "originalPrice": 110,
    "discount": 18,
    "category": "First Aid",
    "subcategory": "Wound Care",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 550,
    "rxRequired": false,
    "description": "A pack of assorted adhesive bandages to cover and protect minor cuts and scrapes.",
    "dosage": "N/A",
    "sideEffects": ["Adhesive allergy in some individuals."],
    "precautions": ["Apply to clean, dry skin. Change dressing daily."]
  },
  {
    "id": 31,
    "name": "Revital H Woman Tablet",
    "manufacturer": "Sun Pharma",
    "price": 310,
    "originalPrice": 340,
    "discount": 9,
    "category": "Women Care",
    "subcategory": "Vitamins",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 180,
    "rxRequired": false,
    "description": "A daily health supplement specially formulated for women, with a blend of vitamins, minerals, and ginseng.",
    "dosage": "One tablet daily after a meal.",
    "sideEffects": ["N/A"],
    "precautions": ["Not for medicinal use."]
  },
  {
    "id": 32,
    "name": "Acne Pimple Patch",
    "manufacturer": "The Face Shop",
    "price": 250,
    "originalPrice": 300,
    "discount": 17,
    "category": "Personal Care",
    "subcategory": "Face Care",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 200,
    "rxRequired": false,
    "description": "Hydrocolloid patches that absorb impurities and protect blemishes from further irritation.",
    "dosage": "Apply one patch over the blemish.",
    "sideEffects": ["N/A"],
    "precautions": ["For external use only. Use on clean, dry skin."]
  },
  {
    "id": 33,
    "name": "Mouthwash Cool Mint",
    "manufacturer": "Listerine",
    "price": 180,
    "originalPrice": 210,
    "discount": 14,
    "category": "Personal Care",
    "subcategory": "Oral Care",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 300,
    "rxRequired": false,
    "description": "Kills 99.9% of germs that cause bad breath, plaque, and gingivitis.",
    "dosage": "Rinse with 20ml for 30 seconds, twice daily.",
    "sideEffects": ["Temporary stinging sensation."],
    "precautions": ["Do not swallow. Not for children under 12."]
  },
  {
    "id": 34,
    "name": "Baby Diapers (Medium)",
    "manufacturer": "Pampers",
    "price": 899,
    "originalPrice": 1050,
    "discount": 14,
    "category": "Baby Care",
    "subcategory": "Diapering",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 100,
    "rxRequired": false,
    "description": "Soft and comfortable diapers with up to 12 hours of dryness protection.",
    "dosage": "N/A",
    "sideEffects": ["Diaper rash if not changed frequently."],
    "precautions": ["Change diaper when wet or soiled."]
  },
  {
    "id": 35,
    "name": "Probiotic Capsules",
    "manufacturer": "Yakult",
    "price": 450,
    "originalPrice": 520,
    "discount": 13,
    "category": "Nutritional Drinks & Supplements",
    "subcategory": "Wellness",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 85,
    "rxRequired": false,
    "description": "A supplement containing live beneficial bacteria to support gut health and digestion.",
    "dosage": "One capsule daily.",
    "sideEffects": ["Initial gas or bloating."],
    "precautions": ["Store in a refrigerator."]
  },
  {
    "id": 36,
    "name": "Vicks VapoRub",
    "manufacturer": "Procter & Gamble",
    "price": 140,
    "originalPrice": 150,
    "discount": 7,
    "category": "Cold & Flu",
    "subcategory": "Nasal Congestion",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 400,
    "rxRequired": false,
    "description": "Provides relief from cough, nasal congestion, body ache, headache, and muscle stiffness.",
    "dosage": "Gently apply on chest, neck, and back for relief.",
    "sideEffects": ["Skin irritation."],
    "precautions": ["Do not use in nostrils or on broken skin."]
  },
  {
    "id": 37,
    "name": "Orsl Liquid 200ml",
    "manufacturer": "Johnson & Johnson",
    "price": 35,
    "originalPrice": 40,
    "discount": 13,
    "category": "Nutritional Drinks & Supplements",
    "subcategory": "Energy Drinks",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 600,
    "rxRequired": false,
    "description": "An electrolyte drink to help restore body fluids and electrolytes lost due to dehydration.",
    "dosage": "Consume as needed to rehydrate.",
    "sideEffects": ["N/A"],
    "precautions": ["Consult a doctor for children or if symptoms persist."]
  },
  {
    "id": 38,
    "name": "Digene Acidity & Gas Relief",
    "manufacturer": "Abbott",
    "price": 120,
    "originalPrice": 135,
    "discount": 11,
    "category": "Stomach Care",
    "subcategory": "Acidity",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 250,
    "rxRequired": false,
    "description": "Provides fast relief from acidity, gas, and indigestion with a scientifically developed combination of active ingredients.",
    "dosage": "Adults: 2-4 tablets, as required.",
    "sideEffects": ["Chalky taste", "Constipation"],
    "precautions": ["Do not take more than 10 tablets in 24 hours."]
  },
  {
    "id": 39,
    "name": "Crepe Bandage",
    "manufacturer": "Hansaplast",
    "price": 150,
    "originalPrice": 180,
    "discount": 17,
    "category": "First Aid",
    "subcategory": "Support & Braces",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 150,
    "rxRequired": false,
    "description": "A stretchable bandage used to create localized pressure for sprains and strains.",
    "dosage": "N/A",
    "sideEffects": ["Skin irritation if wrapped too tightly."],
    "precautions": ["Do not apply too tightly to avoid restricting circulation."]
  },
  {
    "id": 40,
    "name": "Burnol Cream",
    "manufacturer": "Dr. Morepen",
    "price": 85,
    "originalPrice": 95,
    "discount": 11,
    "category": "First Aid",
    "subcategory": "Burn Care",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 200,
    "rxRequired": false,
    "description": "An antiseptic cream for first-degree burns, cuts, and scrapes. Helps prevent infection and soothes the skin.",
    "dosage": "Apply a thin layer to the affected area.",
    "sideEffects": ["Mild stinging sensation."],
    "precautions": ["For minor burns only. Consult a doctor for severe burns."]
  },
  {
    "id": 41,
    "name": "Isabgol Husk",
    "manufacturer": "Psyllium",
    "price": 150,
    "originalPrice": 170,
    "discount": 12,
    "category": "Stomach Care",
    "subcategory": "Digestion",
    "image": "/images/placeholder.jpg",
    "status": "In Stock",
    "unitsAvailable": 280,
    "rxRequired": false,
    "description": "A natural laxative that helps relieve constipation and improve digestive health.",
    "dosage": "1-2 teaspoons mixed in a glass of water, once daily.",
    "sideEffects": ["Bloating", "Gas"],
    "precautions": ["Drink plenty of water throughout the day."]
  },
 
]